[gcc-mips] fix compile error in 64bit system.   ERR MSG: real.h:82: error: size of array 'test_real_width' is negative
when gcc-mips compiling. it's first apply openwrt/toolchain/gcc.../patches.
it not apply package/gcc-mips/patches. so this patch is manuly apply this
patch.

Signed-off-by: Xiangfu Liu <xiangfu@sharism.cc>